spring:
  application:
    name: banking
  datasource:
    url: jdbc:mysql://localhost:3306/banking?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=False
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
server:
  port: 5000